name: Check Build (Develop)

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  build:
    name: 🏗️ Teste de Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./rhizome_app

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './rhizome_app/package-lock.json'

      - name: 📦 Instalar dependências
        run: npm ci

      - name: 🔍 Verificação de Tipos (TypeScript)
        run: npx tsc --noEmit

      - name: 🚀 Executar a Build do Vite
        run: npm run build